### ISSUE TITLE
HopperOptimizations-1.15.2-0.1.14 cause 'Error executing task on Server'

### ISSUE THREAD

**Issue by ArchmageTony** [2No2Name/hopperOptimizations#6]
I can't speak English very well,so I use google translate.   
I update this mod from 0.1.13 to 0.1.14 on my server,then my server will cause 'Error executing task on Server' by 'ArrayIndexOutOfBoundsException'
This is my log.
![image](https://user-images.githubusercontent.com/19744053/74598717-61e43280-50b1-11ea-92bc-b98270a84910.png)
This is the complete log.
[2020-02-14-1.log](https://github.com/2No2Name/hopperOptimizations/files/4209322/2020-02-14-1.log)

**Comment by Heitzenberg** [comment]
+1, I also experienced this.

**Comment by 2No2Name** [comment]
Thanks for the report, I will look into it now.

**Comment by 2No2Name** [comment]
It looks like the steps to reproduce are to open a double chest that a hopper already transferred an item into since the last chunk reload and swap two items inside the player inventory. The mistake seems to be obvious and will be fixed in the next release. Did the problem occur in any other place?

Edit: also found in other player to inventory interactions, for now you can enable the playerInventoryDeoptimization rule work around this

**Comment by Heitzenberg** [comment]
Thanks for the bugfix update!

**Comment by ArchmageTony** [comment]
Thank you! It works well
